# Generated by Django 5.2 on 2026-06-22 14:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("muscle_group", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("barbell", "Barbell"),
                            ("dumbbell", "Dumbbell"),
                            ("cable", "Cable"),
                            ("machine", "Machine"),
                            ("bodyweight", "Bodyweight"),
                            ("other", "Other"),
                        ],
                        default="barbell",
                        max_length=20,
                    ),
                ),
                ("is_global", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exercises",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["created_by"], name="exercises_created_eae801_idx"),
                    models.Index(fields=["is_global"], name="exercises_is_glob_1ee519_idx"),
                ],
            },
        ),
    ]
