# Generated by Django 5.2 on 2026-06-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="foodlogentry",
            new_name="food_log_en_user_id_a3466d_idx",
            old_name="food_log_entries_user_date_idx",
        ),
    ]
