apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-frontend
spec:
  replicas: 1
  selector:
    matchLabels: { app: fitness-frontend }
  template:
    metadata:
      labels: { app: fitness-frontend }
    spec:
      containers:
        - name: caddy
          image: fitness-frontend:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests: { cpu: "10m", memory: "32Mi" }
            limits:   { cpu: "100m",memory: "64Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-frontend
spec:
  selector: { app: fitness-frontend }
  ports:
    - port: 80
      targetPort: 80