# Generated by Django 5.2 on 2026-06-28 17:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_step",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UserEquipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.equipment")),
            ],
            options={
                "db_table": "user_equipment",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "biological_sex",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("height", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("current_weight", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("target_weight", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                (
                    "current_body_type",
                    models.CharField(
                        blank=True,
                        choices=[("lean", "Lean"), ("athletic", "Athletic"), ("bulky", "Bulky"), ("soft", "Soft")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "target_body_type",
                    models.CharField(
                        blank=True,
                        choices=[("lean", "Lean"), ("athletic", "Athletic"), ("bulky", "Bulky"), ("soft", "Soft")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lose_weight", "Lose weight"),
                            ("build_muscle", "Build muscle"),
                            ("maintain_weight", "Maintain weight"),
                            ("improve_fitness", "Improve fitness"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("weekly_change_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("workout_days_per_week", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("session_length_minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "gym_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("commercial", "Commercial"),
                            ("hybrid", "Hybrid"),
                            ("no_gym", "No gym"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "plan_source",
                    models.CharField(
                        blank=True,
                        choices=[("app_generated", "App Generated Plan"), ("build_my_own", "Build My Own Plan")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True, related_name="profiles", through="accounts.UserEquipment", to="accounts.equipment"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.AddField(
            model_name="userequipment",
            name="profile",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.userprofile"),
        ),
        migrations.CreateModel(
            name="UserTargetMuscleGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "muscle_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.musclegroup"),
                ),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.userprofile")),
            ],
            options={
                "db_table": "user_target_muscle_groups",
                "unique_together": {("profile", "muscle_group")},
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_muscle_groups",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", through="accounts.UserTargetMuscleGroup", to="accounts.musclegroup"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userequipment",
            unique_together={("profile", "equipment")},
        ),
    ]
