# Generated by Django 5.2 on 2026-06-22 14:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("session_name", models.CharField(blank=True, default="", max_length=200)),
                ("body_weight_kg", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "body_weight_unit",
                    models.CharField(
                        blank=True, choices=[("kg", "Kilograms"), ("lbs", "Pounds")], max_length=3, null=True
                    ),
                ),
                ("workout_date", models.DateField()),
                ("notes", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workout_sessions",
                "ordering": ["-workout_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order_in_session", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workout_exercises",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "workout_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercises",
                        to="workouts.workoutsession",
                    ),
                ),
            ],
            options={
                "db_table": "workout_exercises",
                "ordering": ["order_in_session"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("set_number", models.IntegerField()),
                (
                    "set_type",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("warmup", "Warmup"),
                            ("dropset", "Dropset"),
                            ("failure", "Failure"),
                        ],
                        default="working",
                        max_length=10,
                    ),
                ),
                ("weight_kg", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                (
                    "weight_unit",
                    models.CharField(
                        blank=True, choices=[("kg", "Kilograms"), ("lbs", "Pounds")], max_length=3, null=True
                    ),
                ),
                ("reps", models.IntegerField()),
                ("rest_time_seconds", models.IntegerField(blank=True, null=True)),
                ("had_spotter", models.BooleanField(default=False)),
                ("paused", models.BooleanField(default=False)),
                ("pause_at_rep", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sets", to="workouts.workoutexercise"
                    ),
                ),
            ],
            options={
                "db_table": "exercise_sets",
                "ordering": ["set_number"],
                "indexes": [models.Index(fields=["workout_exercise"], name="exercise_se_workout_600910_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(fields=["user", "workout_date"], name="workout_ses_user_id_388cd4_idx"),
        ),
        migrations.AddIndex(
            model_name="workoutexercise",
            index=models.Index(fields=["workout_session"], name="workout_exe_workout_0f096c_idx"),
        ),
        migrations.AddIndex(
            model_name="workoutexercise",
            index=models.Index(fields=["exercise"], name="workout_exe_exercis_6bfd73_idx"),
        ),
    ]
